Contributor
jmhodges commented on 14 Aug 2015
It seems that there is some python code that tries to test if a port is open which does not work unless running under sudo. (This also means the integration tests always fail on OS X machines.)
I believe that is being done in order to see if the client can later open that port itself. A nice solution would be to just try to open the port and then handle the failures there, instead. This has the nice property of removing a possible race between the time of port-check and the time of port-allocation where another service could take the port.