Contributor
jdkasten commented on 22 Mar 2015
venv/local/lib/python2.7/site-packages/requests-2.6.0
py2.7.egg/requests/packages/urllib3/util/ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
InsecurePlatformWarning
I received this for (what I believe to be) the first time. I didn't dig too deeply, but it appears that it can be worked around using pyopenssl.