kostyll commented on Sep 27, 2014
Hello, I've get the next problem
response = requests.post(self.url("translate"), data=data)
File "/home/andrew/.config/sublime-text-3/Packages/RusVariablesTranslator/requests/requests/api.py", line 92, in post
return request('post', url, data=data, *_kwargs)
File "/home/andrew/.config/sublime-text-3/Packages/RusVariablesTranslator/requests/requests/api.py", line 48, in request
return session.request(method=method, url=url, *_kwargs)
File "/home/andrew/.config/sublime-text-3/Packages/RusVariablesTranslator/requests/requests/sessions.py", line 451, in request
resp = self.send(prep, *_send_kwargs)
File "/home/andrew/.config/sublime-text-3/Packages/RusVariablesTranslator/requests/requests/sessions.py", line 562, in send
r = adapter.send(request, *_kwargs)
File "/home/andrew/.config/sublime-text-3/Packages/RusVariablesTranslator/requests/requests/adapters.py", line 362, in send
timeout=timeout
File "/home/andrew/.config/sublime-text-3/Packages/RusVariablesTranslator/requests/requests/packages/urllib3/connectionpool.py", line 516, in urlopen
body=body, headers=headers)
File "/home/andrew/.config/sublime-text-3/Packages/RusVariablesTranslator/requests/requests/packages/urllib3/connectionpool.py", line 304, in _make_request
self._validate_conn(conn)
File "/home/andrew/.config/sublime-text-3/Packages/RusVariablesTranslator/requests/requests/packages/urllib3/connectionpool.py", line 722, in _validate_conn
conn.connect()
File "/home/andrew/.config/sublime-text-3/Packages/RusVariablesTranslator/requests/requests/packages/urllib3/connection.py", line 169, in connect
self.sock = ssl.wrap_socket(conn, self.key_file, self.cert_file)
AttributeError: 'NoneType' object has no attribute 'wrap_socket'
....